#!/usr/bin/python3
import random

def reminder():
    items = [
             "You can type 'google <term>' to search from terminal. Instead of 'google', try 'github', 'youtube' or 'wiki'!",
             "You can use 'imgcat <file>' to output an image straight to terminal!"
            ]
    item = random.choice(items)
    print(item)

reminder()
